# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbsurf < Formula
  desc "TUI database explorer with vim-style navigation"
  homepage "https://github.com/jdtoombs/dbsurf"
  version "0.1.3-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.3-alpha/dbsurf_0.1.3-alpha_darwin_amd64.tar.gz"
      sha256 "6f45dd78def684a66bb3ee4d6727d78bafe8c5e13cd99741a5f7cbfbc85cd512"

      def install
        bin.install "dbsurf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.3-alpha/dbsurf_0.1.3-alpha_darwin_arm64.tar.gz"
      sha256 "8cd8bf7553d487ab6e3ae1a2e1d52ee91e9b997edc8c8bb3cc48006e6b4511e5"

      def install
        bin.install "dbsurf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.3-alpha/dbsurf_0.1.3-alpha_linux_amd64.tar.gz"
      sha256 "50853db719b70372dbebea3764e039ebbe17d5e58ca45de472725c1ae8ffb60f"
      def install
        bin.install "dbsurf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.3-alpha/dbsurf_0.1.3-alpha_linux_arm64.tar.gz"
      sha256 "1a807ea078b35884fa021aa834877c3dbef265533f8af3c3fd00c90bc97234a2"
      def install
        bin.install "dbsurf"
      end
    end
  end

  test do
    system "#{bin}/dbsurf", "--version"
  end
end
