# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbsurf < Formula
  desc "TUI database explorer with vim-style navigation"
  homepage "https://github.com/jdtoombs/dbsurf"
  version "0.1.4-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.4-alpha/dbsurf_0.1.4-alpha_darwin_amd64.tar.gz"
      sha256 "1e106507016db9ef7b61913d783f28333238422c652bc61cbb03f22a6639f1ea"

      def install
        bin.install "dbsurf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.4-alpha/dbsurf_0.1.4-alpha_darwin_arm64.tar.gz"
      sha256 "dfb899b8acfe067ea7fcc1817b376c7a6346a7590f84af940603d922b0b118fe"

      def install
        bin.install "dbsurf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.4-alpha/dbsurf_0.1.4-alpha_linux_amd64.tar.gz"
      sha256 "24cb70b409def8eb403188765f9dc452ae158ae5ef0e277775ea3cf0ed4d9bcd"
      def install
        bin.install "dbsurf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdtoombs/dbsurf/releases/download/v0.1.4-alpha/dbsurf_0.1.4-alpha_linux_arm64.tar.gz"
      sha256 "2fb23357c85a015f70eef080c3c7e380448facc9a83f64013e86f6e0f79ad328"
      def install
        bin.install "dbsurf"
      end
    end
  end

  test do
    system "#{bin}/dbsurf", "--version"
  end
end
